{% set data = load_setup_py_data() %}
{% set version = data.get('version') or 'placehold' %}

package:
  name: q2-virsorter2
  version: {{ version }}

source:
  path: ../..

build:
  script: make install

requirements:
  host:
    - python {{ python }}
    - setuptools

  run:
    - python {{ python }}
    - qiime2 {{ qiime2_epoch }}.*
    - q2-types {{ qiime2_epoch }}.*
    - virsorter=2
    - pyhmmer

test:
  requires:
    - coverage
    - pytest-cov
  imports:
    - q2_virsorter2
    - qiime2.plugins.virsorter2
  commands:
    - pytest --cov q2_virsorter2 --cov-report xml:coverage.xml --pyargs q2_virsorter2

about:
  home: https://github.com/bokulich-lab/q2-virsorter2
  license: BSD-3-Clause
  license_family: BSD
